[tool.poetry]
name = "h1st"
version = "0.1.7"
description = "Human-First AI (H1ST)"
authors = ["h1st-ai <engineering@aitomatic.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://h1st.ai"
repository = "https://github.com/h1st-ai/h1st"
include = ["h1st/*"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"

pyarrow = "^7.0.0"
graphviz = "^0.19.1"
lime = "^0.2.0.1"
s3fs = "^2022.1.0"
scikit-fuzzy = "^0.4.2"
scikit-learn = "^1.0.2"
shap = "^0.40.0"
ulid-py = "^1.1.0"
pyyaml = "^6.0"

[tool.poetry.dev-dependencies]
commitizen = "^2.20.5"
pre-commit = "^2.17.0"
pytest = "^7.0.0"
tensorflow = "^2.8.0"
sphinx = "^4.4.0"
sphinx-rtd-theme = "^1.0.0"
pylint = "^2.12.2"

[build-system]
requires = ["poetry-core >= 1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 120
